In [1]:
from src.data_prep.fetch_integrate import get_integrated_data
from src.data_prep.engineer import test_and_engineer
import pandas as pd

C:\Users\fezzati\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = get_integrated_data()
df.head()

----------- Fetching Walmart Data Set -----------
INFO >> Walmart dataset already cached at ../../data/raw/walmart
==============================
Fetching Walmart Sales Data Set
==============================
INFO >> All FRED series already cached at ../../data/raw/fred
==============================
Integrating Data Sets
==============================
INFO >> Date converted to YearMonth for Walmart_Sales.
INFO >> Merged monthly series 'consumer_sentiment'.
INFO >> Merged monthly series 'advanced_retail_sales'.
INFO >> Merged monthly series 'personal_consum_expend'.
INFO >> Merged monthly series 'personal_saving_rate'.
INFO >> Merged monthly series 'producer_price_index'.
INFO >> Merged monthly series 'effective_federal_fund'.
INFO >> Merged quarterly series 'household_dept_srvc_ratio' via merge_asof.
INFO >> Integration complete. Shape: (6435, 15)

d:\Codes\Python\WDF\src\data_prep\fetch_integrate.py:143: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  walmart_df["Date"] = pd.to_datetime(walmart_df["Date"])

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,consumer_sentiment,advanced_retail_sales,personal_consum_expend,personal_saving_rate,producer_price_index,effective_federal_fund,household_dept_srvc_ratio
0,5,2010-01-10,283178.12,0,71.10,2.603,212.226946,6.768,74.4,302325.0,10056.1,5.6,181.9,0.11,14.51494
1,15,2010-01-10,566945.95,0,59.69,2.840,132.756800,8.067,74.4,302325.0,10056.1,5.6,181.9,0.11,14.51494
2,42,2010-01-10,481523.93,0,86.01,3.001,126.234600,9.003,74.4,302325.0,10056.1,5.6,181.9,0.11,14.51494
3,33,2010-01-10,224294.39,0,91.45,3.001,126.234600,9.265,74.4,302325.0,10056.1,5.6,181.9,0.11,14.51494
4,36,2010-01-10,422169.47,0,74.66,2.567,210.440443,8.476,74.4,302325.0,10056.1,5.6,181.9,0.11,14.51494

In [3]:
print(f'{10*"="}')

==========

In [ ]:
df = engineer(df)
df.head()

Store Levene's p-value: 0.0000
INFO >> Joint normality and homogeneity conditions not met. Continue with <Kruskal-Wallis, Mann-Whitney U>, non-parameteric test.
INFO >> At least one store has a significant difference in sales with others.
INFO >> Correlated but non-significant numeric features are: ['effective_federal_fund', 'producer_price_index', 'Temperature']

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,consumer_sentiment,advanced_retail_sales,personal_consum_expend,personal_saving_rate,producer_price_index,effective_federal_fund,household_dept_srvc_ratio,sin_week,cos_week,rolling_4_mean
0,1,2010-01-10,1453329.50,0,71.89,2.603,211.671989,7.838,74.4,302325.0,10056.1,5.6,181.9,0.11,14.51494,0.120208,0.992749,1.538171e+06
1,1,2010-02-04,1594968.28,0,62.27,2.719,210.820450,7.808,73.6,302310.0,10093.4,5.3,181.0,0.13,14.51494,0.566701,0.823923,1.538171e+06
2,1,2010-02-07,1492418.14,0,80.91,2.669,211.223533,7.787,73.6,302310.0,10093.4,5.3,181.0,0.13,14.51494,0.566701,0.823923,1.538171e+06
3,1,2010-02-19,1611968.17,0,39.93,2.514,211.289143,8.106,73.6,302310.0,10093.4,5.3,181.0,0.13,14.51494,0.746972,0.664856,1.538171e+06
4,1,2010-02-26,1409727.59,0,46.63,2.561,211.319643,8.106,73.6,302310.0,10093.4,5.3,181.0,0.13,14.51494,0.821476,0.570243,1.538171e+06